### PR TITLE
Implement logic for transition dialog.

### LINKED ISSUE #2612: Transition UI
As a user I want to transfer my gateway to use webthings.io services so that I can continue to receive software updates and access my gateway remotely.

The Mozilla IoT remote access service and automatic software updates are being [discontinued](https://discourse.mozilla.org/t/an-important-update-on-mozilla-webthings/67764/11). This UI in the gateway notifies users of this change and guides them through the transfer to replacement community-run services at webthings.io.

Draft UX specification [here](https://docs.google.com/presentation/d/1X5pfyQX-4oeRcNxxPf5wtpt2MgYi5VBBENIZkJX6Axc/edit?usp=sharing).

SVG assets incoming...

### PR DESCRIPTION
**Pull request by mrstegeman**
Closes #2612

### CODE REVIEW

**Review by benfrancis — APPROVED** [review]
Nice work on getting this working. I had a bunch of comments about the code but realised they were all about coding style and API design so decided they're not really important given this code is only temporary.

I've tested this quite thoroughly and can't find any major bugs.

One slight UI bug: It's possible to get the UI into a state where the #update-message-area and #action-required-area divs both appear and overlap each other when the page first loads after a 1.0 upgrade, which looks broken (I'm working on steps to reproduce because it didn't happen the second time I tried it and I'm not sure what I did differently).

Ideally we'd have them stack on top of each other along the y axis but I can't spot a quick fix for that. Worst case we could just give the update dialog a darker (and opaque) background colour (#48779a) with darker buttons (#315169) so the boundary between the two can be seen.

I did spot an exception in the console at one point about a 500 error, but I haven't been able to reproduce it again. I'll let you know if I manage it.

I have a couple of comments about the transition emails that are sent out, but I'll share those separately as they don't relate to this PR.

**Comment by benfrancis** [comment]
> One slight UI bug: It's possible to get the UI into a state where the #update-message-area and #action-required-area divs both appear and overlap each other

FWIW, I haven't been able to reproduce this again.

**Comment by mrstegeman** [comment]
> Nice work on getting this working. I had a bunch of comments about the code but realised they were all about coding style and API design so decided they're not really important given this code is only temporary.

Yeah, it was definitely quick and dirty.
 
> One slight UI bug: It's possible to get the UI into a state where the #update-message-area and #action-required-area divs both appear and overlap each other when the page first loads after a 1.0 upgrade, which looks broken (I'm working on steps to reproduce because it didn't happen the second time I tried it and I'm not sure what I did differently).

That's easy to reproduce. Just run `npm start` again and soft-refresh the UI. I thought about adding some logic to not show the transition banner when the reload banner is active. What do you think about that?

**Comment by benfrancis** [comment]
> That's easy to reproduce. Just run npm start again and soft-refresh the UI. I thought about adding some logic to not show the transition banner when the reload banner is active. What do you think about that?

Yep that sounds ideal.

**Comment by mrstegeman** [comment]
> > That's easy to reproduce. Just run npm start again and soft-refresh the UI. I thought about adding some logic to not show the transition banner when the reload banner is active. What do you think about that?
> 
> Yep that sounds ideal.

Done.

**Pull request merged**
