### PR TITLE
Observe properties - closes #2982, closes #2983

### LINKED ISSUE #2982: Implement `observeproperty` operation
As a developer consuming the gateway API, I want to be able to observe the value of a property so that I can be notified when it changes rather than having to poll the property resource.

Implement the `observeproperty` and `unobserveproperty` protocol bindings from the HTTP SSE Profile, as defined in https://w3c.github.io/wot-profile/#observeproperty

### LINKED ISSUE #2983: Implement `observeallproperties` operation
As a developer consuming the gateway API, I want to be able to observe the value of all properties of a Thing so that I can be notified when one changes rather than having to poll the properties resource

Implement the `observeallproperties` and `unobserveallproperties` protocol bindings from the HTTP SSE Profile, as defined in https://w3c.github.io/wot-profile/#observeallproperties

### PR DESCRIPTION
**Pull request by benfrancis**
This PR implements the `observeproperty`, `unobserveproperty`, `observeallproperties` and `unobserveallproperties` operations of the W3C WoT [HTTP SSE Profile](https://w3c.github.io/wot-profile/#sec-http-sse-profile) (closes #2982 and #2983).

This will enable WoT Consumers to observe property changes over Server-Sent Events, as an alternative to using the (currently non-standard) WebSockets subprotocol or polling a property using the `readproperty` operation, and is the last set of features needed to be compliant with the HTTP SSE Profile (I'll add the profile member later in #2909).

This PR includes some refactoring including:
- Splitting out property URL handlers from the `ThingsController` into a new `PropertiesController`
- Splitting out property, action and event integration tests out of things-test.ts which was getting very large

Those refactorings are in separate commits for readability. I would also like to refactor thing.ts to extract out a lot of duplicated Thing Description parsing logic, but I've filed a [separate issue](https://github.com/WebThingsIO/gateway/issues/3076) for that.

The PR adds routes to listen for Server-Sent Event connections on `/things/:thingId/properties/:propertyId` and `/things/:thingId/properties/` endpoints (using HTTP content negotiation to differentiate from the JSON responses), and adds Forms to Thing Descriptions to expose the new operations.

- [x]  Implement `observeproperty`
- [x] Implement `unobserveproperty`
- [x] Implement `observeallproperties`
- [x] Implement `unobserveallproperties`
- [x] Expose observe operations in Thing Descriptions
- [x] Write integration tests

### CODE REVIEW

**Comment by benfrancis** [comment]
@relu91 I would be extremely grateful if you could find time to review this.

**Comment by benfrancis** [comment]
If @relu91 isn't able to get to this, might you be able to find time to review, @tim-hellhake?

**Review by relu91 — APPROVED** [review]
Really sorry for being late. From what I am concerned the changes look good! I would have liked to test it with node-wot, but I am currently on a Windows machine and fought a bit to set up the gateway inside WSL last time... Therefore I don't have the bandwidth to do it right now. I hope we can do a cross-check in the future (maybe a Testfest).

**Comment by benfrancis** [comment]
@relu91 Great, thank you. Look forward to interop testing.

**Pull request merged**
